# server config
server:
  port: 8080
  context-path: /spring-boot-sample
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
    path: /error
# log
logging:
  path: /logs
  file: spring-boot-sample.log
  level:
    org.springframework.web: DEBUG
    dao: DEBUG
    org.mybatis.spring.SqlSessionFactoryBean: DEBUG
    org.apache.ibatis.thread: DEBUG
    com.whatlookingfor.sample: DEBUG
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/workfocus
    username: root
    password: 123456
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    #配置初始化大小、最小、最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  mvc:
    view:
      suffix: /templates/
      prefix: .ftl
  freemarker:
    cache: false
    checkTemplateLocation : false
    settings:
      template_update_delay : 0
      default_encoding : UTF-8
    request-context-attribute: request
multipart: #文件上传
  max-file-size: 30MB #指定文件大小最大值,默认为1MB
  max-request-size: 30MB #指定每次请求的最大值，默认为10MB

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.whatlookingfor.sample.**.entity
  configLocation: classpath:/mybatis-config.xml
#以下为系统定义
mybatisRefresh: #mybatis xml实时刷新的配置
  enabled: true #是否支持xml实时刷新,部署时,改为false
  delaySeconds: 5  #project start time[项目启动时间]
  sleepSeconds: 2 # xml scanning interval time[扫描间隔时长]
  mappingPath: mapper # xml file's path

#swagger ui 定义参数
swagger:
  title: API docs #标题
  description: SWAGGER DEMO #描述
  version: 1.0-SNAPSHOT #版本号
  termsOfServiceUrl: https://github.com/whatlookingfor
  license: The Apache License, Version 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html #license url
  author: Jonathan  #作者
  url: https://github.com/whatlookingfor #链接
  email: whatlookingfor@gmail.com  #邮箱
  apiPath: /api/.*,/demo/.*,/swagger/.* #多个以','隔开